### ISSUE TITLE
Sugestion/ Feature Request: Improve Context menu  functionality for Crafting lists

### ISSUE THREAD

**Issue by MDlumia** [PunishXIV/Artisan#106]
So this is just a few ideas that i thought would make the context menu better.  for the crafting list menu.  Maybe have the standard New list option, then add a option like Add to "Certant" list  and then how ever you like to do  the ui give us the option to chose the list and how many of the craft we want to add.  I find its super annoying having to click the same option repeatedly for  as many crafts as i want to make.  so this would be a pretty big QoL fix.

**Comment by Taurenkey** [comment]
Context menus aren't designed to do that sort of thing. They're just quick shortcuts to a thing. I personally hate them for making lists because of that and the feature only exists because it was requested. You're better off using any of the other ways to build lists for this sort of thing, notably the list editor itself.
