### ISSUE TITLE
[Feature Requests]: Condition for Exact Step Count and Replace with 'Touch Combo'

### ISSUE THREAD

**Issue by vitharr137** [PunishXIV/Artisan#97]
Hello!

Two recommends would greatly benefit the optimizing of imported macros:

Setting a condition to match a specified exact step of a given macro or skip. Scenario: using a conditional Excellent step to consume it with Tricks and then a Poor condition Innovation to prepare for the Great Strides -> Byregot combo can be triggered if the last act before the conditional Excellent Tricks was itself an Excellent proc. (Also possible to fix this by adding a conditional of if the given buff remains for > X steps)

Adding a Replace Action similar to 'Artisan Recommendation' where instead it steps through the Touch Combo only of Basic -> Standard -> Advanced depending on what stage it is on. Scenario: Setting the Upgrade Quality Actions flag on a Macro that utilizes the Touch Combo will fail if the combo is broken and points are consumed by an un-combo'd Standard or Advanced touch instead of resetting to Basic

Thank you!

**Comment by Taurenkey** [comment]
My concern with the first one is adding "dumb logic" to macros can backfire. Whilst your example is less likely to break a macro (since tricks + innovation is still a CP gain with no durability change), other setups could break it more easily. For example, maybe you didn't have it do tricks on excellent, maybe you select byregot's. Several things could go wrong here, breaking due to durability, bricking the macro because you spent IQ stacks early, running out of CP for a mend etc. The amount of flexibility you can actually get out of macros is limited before you're better off just writing a solver for it instead.

The second one I'll look at adding a "Touch Combo" action, which does the appropriate step of the 3-step touch combo so that way you're at least not going CP negative if it happens to upgrade on the Basic Touch.
